### ISSUE TITLE
Input data

### ISSUE THREAD

**Issue by sirisha-8** [kidozh/rnn_in_prediction_tool_wear#2]
Hi,
In 2010 PHM society challenge , The input data provided by them contains 7 columns,But in c1,c4,c6  (with columns mentioned as flute_1,flute_2 ...) .There are actually 3 columns.Could you @kidozh provide more insights on the input data and what flute1,flute2 corresponds to   

Thanks.

**Comment by kidozh** [comment]
We use max tool wear for every cut because it indicates remaining useful life.

In our data.py, there is a corresponding code, and you may get detailed information from that.

best regards

**Comment by yue5667** [comment]
你好，本人新手小白，不知道该项目从哪里开始执行，可否告知一下？感谢
![image](https://user-images.githubusercontent.com/58220187/70762033-29ab3580-1d8a-11ea-8dc9-b1d32169c028.png)

**Comment by kidozh** [comment]
@yue5667 在main.py直接运行就可以了。

还有就是建议开一个新的issue，因为你的问题也会被推送到这个issue原始的提出人这，可能会给他人造成一定的打扰，我当时以为还有后续，忘了关这个issue了。
