### ISSUE TITLE
unable to open file: name = 'Simple_10_20_Separate_RNN_Depth_5_hidden_dim_128.kerasmodel'

### ISSUE THREAD

**Issue by ysdxzhangqin** [kidozh/rnn_in_prediction_tool_wear#4]
您好！在我运行代码时出现了这样的错误，可否告知相关的解决方案
![1](https://user-images.githubusercontent.com/49009462/88185344-6a472780-cc66-11ea-8fd4-17c7bd7aa59f.png)

**Comment by kidozh** [comment]
很抱歉，你可以参考 issue #1 来解决这个问题。

**Comment by ysdxzhangqin** [comment]
感谢您的帮助，问题已经解决

**Comment by yuhaoxu99** [comment]
您好，请问OSError: No file or directory found at Simple_2_5_Separate_RNN_Depth_5_hidden_dim_128.kerasmodel 这个错误，通过issue#1的解决办法好像还是行不通，请问应该怎么解决呀？
